version: '2.2'
services:

  bot:
    ports:
      - "433:433"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit


  rabbit:
    image: docker.io/bitnami/rabbitmq:3.7.8-debian-9
    hostname: rabbit
    volumes:
      - ${RABBITMQ_DATA:-./rabbitmq/data}:/var/lib/rabbitmq
    restart: on-failure
    healthcheck:
      test: "rabbitmqctl node_health_check"
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"