bot:
  token: ${BOT_TOKEN:1038686725:AAHN7ODOL8AR7-zGDZ5nUAptWb-_DtUzUpw}
  username: ${BOT_NAME:MD_stand_bot}
proxy:
  host: 159.8.145.110
  port: 1080
  user: soksuser
  password: Welcome123

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info